// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AccordionController from './accordion_controller';
application.register('accordion', AccordionController);

import ChatInputController from './chat_input_controller';
application.register('chat-input', ChatInputController);

import ChatPanelController from './chat_panel_controller';
application.register('chat-panel', ChatPanelController);

import DropdownController from './dropdown_controller';
application.register('dropdown', DropdownController);

import FileDropController from './file_drop_controller';
application.register('file-drop', FileDropController);

import FlashController from './flash_controller';
application.register('flash', FlashController);

import FormSubmitController from './form_submit_controller';
application.register('form-submit', FormSubmitController);

import HelloController from './hello_controller';
application.register('hello', HelloController);

import ImageSliderController from './image_slider_controller';
application.register('image-slider', ImageSliderController);

import MobileMenuController from './mobile_menu_controller';
application.register('mobile-menu', MobileMenuController);

import ModelViewerController from './model_viewer_controller';
application.register('model-viewer', ModelViewerController);

import MorphProtectionController from './morph_protection_controller';
application.register('morph-protection', MorphProtectionController);

import NumberStepperController from './number_stepper_controller';
application.register('number-stepper', NumberStepperController);

import PhotoPreviewController from './photo_preview_controller';
application.register('photo-preview', PhotoPreviewController);

import Select2Controller from './select2_controller';
application.register('select2', Select2Controller);

import SelectOptionController from './select_option_controller';
application.register('select-option', SelectOptionController);

import TurboFormController from './turbo_form_controller';
application.register('turbo-form', TurboFormController);

import TurboModalController from './turbo_modal_controller';
application.register('turbo-modal', TurboModalController);
