// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import FlashController from './flash_controller';
import FormSubmitController from './form_submit_controller';
import HelloController from './hello_controller';
import DropdownController from './dropdown_controller';
import MobileMenuController from './mobile_menu_controller';
import FileDropController from './file_drop_controller';
import TurboModalController from './turbo_modal_controller';
import TurboFormController from './turbo_form_controller';
import ImageSliderController from './image_slider_controller';
import ModelViewerController from './model_viewer_controller';
import MorphProtectionController from './morph_protection_controller';
import Select2Controller from './select2_controller';
import PhotoPreviewController from './photo_preview_controller';
import SelectOptionController from './select_option_controller';
import ChatPanelController from './chat_panel_controller';
import ChatInputController from './chat_input_controller';
import NumberStepperController from './number_stepper_controller';
import AccordionController from './accordion_controller';

application.register('number-stepper', NumberStepperController);
application.register('accordion', AccordionController);
application.register('dropdown', DropdownController);
application.register('image-slider', ImageSliderController);
application.register('file-drop', FileDropController);
application.register('flash', FlashController);
application.register('form-submit', FormSubmitController);
application.register('hello', HelloController);
application.register('mobile-menu', MobileMenuController);
application.register('turbo-modal', TurboModalController);
application.register('turbo-form', TurboFormController);
application.register('model-viewer', ModelViewerController);
application.register('morph-protection', MorphProtectionController);
application.register('select2', Select2Controller);
application.register('select-option', SelectOptionController);
application.register('photo-preview', PhotoPreviewController);
application.register('chat-panel', ChatPanelController);
application.register('chat-input', ChatInputController);
