# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Enforce compact style: `class Home::Operation::Index` instead of nested modules
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120