# frozen_string_literal: true

require 'active_support/core_ext/integer/time'

Rails.application.configure do
  # Configure 'rails notes' to inspect Cucumber files
  config.annotations.register_directories('features')
  config.annotations.register_extensions('feature') { |tag| /#\s*(#{tag}):?\s*(.*)$/ }

  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join('tmp/caching-dev.txt').exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { 'cache-control' => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  config.cache_store = :solid_cache_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :minio

  # Active Storage URL strategy depends on how the app is fronted:
  #
  # - bin/dev fronts the app with Caddy over HTTPS (https://dev.applymate.io). A redirect
  #   to MinIO's plain-http localhost:9000 URL is blocked by the browser as mixed content,
  #   so attachments must be *proxied* (streamed through the app on the same HTTPS origin).
  #   Procfile.dev sets ACTIVE_STORAGE_PROXY=true to opt into this.
  # - Conductor workspaces serve plain http://localhost:<port> (no Caddy), where a redirect
  #   to http://localhost:9000 is same-scheme and works fine. Proxy mode there streams every
  #   image through a Puma thread, so a page full of logos can saturate the pool and deadlock
  #   the code reloader (silent infinite load). So default to redirect — the lighter path.
  if ENV['ACTIVE_STORAGE_PROXY'] == 'true'
    config.active_storage.resolve_model_to_route = :rails_storage_proxy
  end

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Use Solid Queue in development (same as production) for Mission Control visibility.
  config.active_job.queue_adapter = :solid_queue

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  config.hosts << 'localhost'
  config.hosts << 'staging.applymate.local'
  config.hosts << 'applymate.local'
  config.hosts << 'applymate.io'
  config.hosts << 'dev.applymate.io'
  config.hosts << ENV['APP_HOST'] if ENV['APP_HOST']

  _stdout_logger = ActiveSupport::Logger.new($stdout)
  _file_logger   = ActiveSupport::Logger.new(Rails.root.join('log', 'development.log'))
  # Strip ANSI colour codes so Promtail can parse structured JSON lines cleanly
  _file_logger.formatter = proc { |_sev, _t, _prog, msg| "#{msg.to_s.gsub(/\e\[[0-9;]*m/, '')}\n" }
  config.logger  = ActiveSupport::BroadcastLogger.new(_stdout_logger, _file_logger)
  config.log_level = :info

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # config.active_record.strict_loading_by_default = true
end
